name: bioinfo-forum
channels:
  - conda-forge
  - bioconda
dependencies:
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - joblib
  - jupyter
  - conda-forge::scanpy
  - python-igraph
  - leidenalg
  - scikit-image
  - conda-forge::muon
  - loompy
  - pooch
